Add Terms of Use
sfcc-unofficial/docs pull request #3
Opened 2020-10-07 15:45 UTC by sholsinger

This PR shall be left open for a period of 7 days to collect community feedback.

Please comment with any adjustments you may desire.

2020-10-07 18:39 UTC, matthewrose requested changes
Looks great! Found one typo that needs to be fixed but I agree with everything that was written here.

2020-10-07 18:39 UTC, matthewrose commented on terms-of-use.md
> +You agree that no professional recruiting shall be performed within the community. Professional recruiting shall be considered as behaviors typically performed by a recruitng profession including, bu
Typo for "recruitng" here

2020-10-08 00:27 UTC, Gektorian approved these changes

2020-10-08 17:43 UTC, ilyaem approved these changes

2020-10-09 09:32 UTC, jbachelet commented
Love it!

2020-10-13 19:32 UTC, BeSublime approved these changes

2020-10-14 18:01 UTC, merged